### ISSUE TITLE
Make fields non-searchable / non-sortable

### ISSUE THREAD

**Issue by michb** [numero2/contao-isotope-simple-erp#2]
It does not make any sense to search in this fields or use them for sorting.

![image](https://user-images.githubusercontent.com/17873830/32724728-c4e6e054-c872-11e7-9dc0-f716a0ff365b.png)

**Comment by bennyborn** [comment]
Sorting by `simple_ero_count` may come in handy. Just removed it from searching and `simple_erp_disable_on_zero` entirely.
